### ISSUE TITLE
Fix registration or setup errors for the migration to 1.18.2 to 1.20.1

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#100]
This may also cover anything not covered by:

#96 Fix errors in `chessmod.client.gui` and `chessmod.client.render`
#98 Fix errors related to networking changes between 1.18.2 and 1.20.1

**Comment by riri404** [comment]
Registration.java:

- [ ]  Fix SoundEvent. This can Be done by looking at source code of open source 1.20 projects (such as Rats)
