### ISSUE TITLE
I think there's an issue with Advancement in many versions

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#141]
I think we need to check if the advancement is working in each version. Basically, it should give an advancement the first time you get a wood chessboard in your inventory, but it many versions it gives the advancement whenever you pick anything up (or maybe never). This was reported and fixed as #90 but I think the source of the error is variance in the format (I hope), but either way resulted in an always true or never true criteria. 

* [x] Check which versions this applies to
* [x] Fix in each broken version

**Comment by Captaintom14** [comment]
1.20 is ok.

**Comment by Captaintom14** [comment]
1.19 is ok.

**Comment by Captaintom14** [comment]
1.18 is ok

**Comment by Captaintom14** [comment]
1.17 is ok.

**Comment by Captaintom14** [comment]
1.16 is ok.

**Comment by Captaintom14** [comment]
1.15 is ok.

**Comment by Captaintom14** [comment]
1.14 is ok.
