### ISSUE TITLE
Create `ResearchMilestoneSummer2023` branches for each version

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#142]
I'm thinking that we'll want ResearchMilestone branches to be fixed for 0.616. This'll allow version-specific fixes that'll let us focus on framework/mapping changes. It'll also let us normalize approaches (e.g. in 1.14.1 where I did rotation in a totally different way, but there was probably a similar way to how it was done in 1.15.2). 

This will let is move forward on the actual production branches, but still maintain the reference-versions for this research project, and even update it independently if we so choose (if some of those posted bugs get fixed and we just want them in, though I'm thinking this lets us avoid that)

 * [x] Make ResearchMilestoneSummer2023-1.20.1-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.19.4-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.18.2-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.17.1-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.16.5-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.15.2-0.616 branch
 * [x] Make ResearchMilestoneSummer2023-1.14.1-0.616 branch

**Comment by Captaintom14** [comment]
Branch ResearchMilestoneSummer2023 1.20 is out

**Comment by Captaintom14** [comment]
Branch ResearchMilestonesSummer2023 1.19 is out

**Comment by Captaintom14** [comment]
Branch ResearchMilestonesSummer2023 1.18 is out

**Comment by Captaintom14** [comment]
Branch ReasearchMilestonesSummer2023 1.17 is out

**Comment by Captaintom14** [comment]
Branch ResearchMilestonesSummer2023 1.16 is out

**Comment by Captaintom14** [comment]
Branch ResearchMilestonesSummer2023 1.15 is out

**Comment by Captaintom14** [comment]
Branch ResearchMilestonesSummer2023 1.14 is out
