### ISSUE TITLE
Stub Chessboards don't have pieces showing

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#143]
Not sure which versions don't have this or why, I thought maybe it never happened, but the ChessMod curseforge page has images of it and I think it works in 1.16.5. So, we probably want to figure out where it's broken, then fix it:

 * [x] Check 1.20.1
 * [x] Check 1.19.4
 * [x] Check 1.18.2
 * [x] Check 1.17.1 - Broken, @Captaintom14 noted this while wrapping the version
 * [x] Check 1.16.5
 * [x] Check 1.15.2
 * [x] Check 1.14.4
 
 Once we make the determination of which versions have this broken, we should probably ticket that and then fix it.

**Comment by Captaintom14** [comment]
The pieces do not show in 1.19.4.

**Comment by Captaintom14** [comment]
The pieces do not show in 1.20.1

**Comment by Captaintom14** [comment]
The pieces do not show in 1.18.2

**Comment by Captaintom14** [comment]
The pieces do not show in 1.15

**Comment by Captaintom14** [comment]
The pieces do show in 1.16

**Comment by Captaintom14** [comment]
The pieces do not show in 1.14

**Comment by Captaintom14** [comment]
In general, the Cheese, AI and Puzzle do not have pieces on the board.

**Comment by Captaintom14** [comment]
The pieces are now shown in different versions now.
