### ISSUE TITLE
Linking boards needs to reset state on the second board

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#166]
Currently, if the state on both boards is the same (ish) it's probably ok. However, you can link boards with different state and then a move will run moveSafely for both, and only work for one, which is annoying. We need a setter that is public for QuantumChessBoardEntity that takes care of the cloning process, call it quantumImprint and pass it a QuantumChessBoardEntity and then we don't have to worry about what else we need to clone down the road for other boards :D

**Comment by riri404** [comment]
Will have to ask for more instrctions for this issue. So far I created a skeleton for the quantumImprint() but if I understand well, we will need to deep cope the state before linking. I will push now what I added. Also I was reading and taking notes (especially NBT) on your new addition to the code and I added some comments to help me understand better.
