### ISSUE TITLE
Particle effect for linked board idea for consideration

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#174]
Have a particle beam that quickly fades in the direction of the board. Maybe color code it for what world it's in, though that could be tricky with mod-added worlds, so maybe one color in the direction if it's in the same world and another color if it's in a different world (e.g. board one in overworld and board two in nether).

**Comment by riri404** [comment]
light beam to tell directions, astral sorcery has a bunch of custom beams might be helpful to check out, writing that down to remember

**Comment by riri404** [comment]
I just thought of something, do you want the beam to be vertical like the end crystal beam or horizontal astral sorcery style? also do we want something like the enchantment glint to indicate that the tables are linked?

**Comment by ramou** [comment]
I thought the enchantment glint for indication of linking was likely an easy way to do it. As for the beam, I wanted it between the two boards, or extending as if it were connecting them, but alpha-ing off very quickly (like a block or so)
