### ISSUE TITLE
Need to close and re-open Gold Chessboard to change turns in single-player

### ISSUE THREAD

**Issue by ramou** [ramou/FirstMod#93]
This seems familiar. I think it works in SMP and I just did something grungy which breaks it for single-player.

Check which versions still have this bug. It appears that not all of them do. I think it happened as of 1.17 or 1.18. I've labeled this issue with those I've confirmed have the bug.

 * [x] Check for bug in 1.18.2-0.616
 * [x] Check for bug in 1.17.1-0.616

1.19 and 1.20 definitely have and 1.14/15/16 do not appear to have it.

 * [x] Fix for bug in 1.20.1-0.616
 * [x] Fix for bug in 1.19.2-0.616
 * [x] Fix for bug in 1.18.2-0.616
 * [x] Fix for bug in 1.17.1-0.616

**Comment by Captaintom14** [comment]
1.17 has the bug.

**Comment by Captaintom14** [comment]
1.18 has the bug.

**Comment by Captaintom14** [comment]
1.17  is fixed.

**Comment by Captaintom14** [comment]
1.18 is fixed

**Comment by Captaintom14** [comment]
1.19 is fixed.

**Comment by Captaintom14** [comment]
1.20 is fixed.
